get_filename_component(_self_dir ${CMAKE_CURRENT_LIST_FILE} PATH)

ExternalProject_Add(hdf5
  DOWNLOAD_DIR ${download_dir}
  URL ${hdf5_url}
  URL_HASH SHA256=${hdf5_sha256}
  BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/hdf5"
  INSTALL_DIR "${OpenChemistry_INSTALL_PREFIX}"
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
)
