ExternalProject_Add(pcre
  DOWNLOAD_DIR ${download_dir}
  URL ${pcre_url}
  URL_MD5 ${pcre_md5}
  BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/pcre"
  INSTALL_DIR "${OpenChemistry_INSTALL_PREFIX}"
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
    -DPCRE_SUPPORT_LIBREADLINE:BOOL=OFF
)
