# Pick out the modules used in MongoChem and AvogadroLibs only.
set(_source "${CMAKE_CURRENT_SOURCE_DIR}/VTK")
set(_build "${CMAKE_CURRENT_BINARY_DIR}/VTK")

unset(_deps)
add_optional_deps(_deps "zlib" "eigen")

ExternalProject_Add(VTK
  SOURCE_DIR ${_source}
  BINARY_DIR ${_build}
  CMAKE_CACHE_ARGS
    ${OpenChemistry_DEFAULT_ARGS}
    -DBUILD_TESTING:BOOL=OFF
    -DVTK_ENABLE_LOGGING:BOOL=OFF
    -DVTK_ENABLE_REMOTE_MODULES:BOOL=OFF
    -DVTK_GROUP_ENABLE_Imaging:STRING=DONT_WANT
    -DVTK_GROUP_ENABLE_Rendering:STRING=DONT_WANT
    -DVTK_GROUP_ENABLE_StandAlone:STRING=DONT_WANT
    -DVTK_GROUP_ENABLE_Views:STRING=DONT_WANT
    -DVTK_GROUP_ENABLE_Qt:STRING=DONT_WANT
    -DVTK_GROUP_ENABLE_Web:STRING=DONT_WANT
    -DVTK_MODULE_ENABLE_VTK_DomainsChemistry:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_DomainsChemistryOpenGL2:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_ViewsContext2D:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_ChartsCore:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_RenderingVolumeOpenGL2:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_RenderingContextOpenGL2:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_GUISupportQt:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_RenderingQt:STRING=YES
    -DVTK_MODULE_ENABLE_VTK_ViewsInfovis:STRING=NO
    -DVTK_MODULE_ENABLE_VTK_RenderingFreeTypeOpenGL2:STRING=YES
    ${OpenChemistry_THIRDPARTYLIBS_ARGS}
    -DVTK_MODULE_USE_EXTERNAL_VTK_zlib:BOOL=ON
    -DVTK_MODULE_USE_EXTERNAL_VTK_eigen:BOOL=ON
    -DVTK_BUILD_QT_DESIGNER_PLUGIN:BOOL=OFF
    -DVTK_QT_VERSION:STRING=${QT_VERSION}
  DEPENDS
    ${_deps}
  )
